# Generated by Django 2.0.3 on 2019-12-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0014_area_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='productcat',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='saleproducts',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='saleproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='saleproducts',
            name='brand_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='saleproducts',
            name='product_model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='saleproducts',
            name='product_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCat',
        ),
    ]
