# Generated by Django 2.0.3 on 2019-12-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0015_auto_20191203_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproducts',
            name='next_installment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
