# Generated by Django 2.0.3 on 2019-12-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0016_auto_20191203_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproducts',
            name='total_installment',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
