# Generated by Django 2.0.3 on 2019-12-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0017_saleproducts_total_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentcollection',
            name='total_installment',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
