# Generated by Django 2.0.3 on 2019-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0019_auto_20191204_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproducts',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
