# Generated by Django 2.0.3 on 2019-12-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0021_auto_20191205_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brancheusers',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
